### ISSUE TITLE
Issues with chromedriver and path

### ISSUE THREAD

**Issue by MattLahoff** [nickconnors/RTX-3070-Best-Buy-Bot#20]
Trying to get the script to work. I edited it with the correct path to chromedriver (c:\bin) but I still get the same error. I also added it to the environmental variables. Can anyone help?

PS C:\Users\username\Downloads\RTX-3070-Best-Buy-Bot-main> python bot.py
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\Downloads\RTX-3070-Best-Buy-Bot-main\bot.py", line 11, in <module>
    driver = webdriver.Chrome(PATH)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

PS C:\Users\username\Downloads\RTX-3070-Best-Buy-Bot-main>

**Comment by LanaDelSlay** [comment]
This looks like you haven't put the chromedriver.exe in it's proper location! download it put it here C:\Program Files (x86)\ChromeDriver\chromedriver.exe
